/**
 * Tier 0-3 캐릭터 데이터베이스
 * KR ↔ EN ↔ CN 이름 매핑 + 나무위키 URL + 팩션 + 티어
 *
 * Tier 0 (20명): 수작업 soul.md — 핵심 인물
 * Tier 1 (65명): AI + 검수 soul.md — 주요 인물
 * Tier 2 (76명): ROTK11 능력치 기반 확장 — 보조 인물
 * Tier 3 (340명): ROTK 10/11/12 중 2개 이상 등장 — 확장 인물
 */

/** @typedef {{ name_kr: string, name_en: string, name_cn: string, courtesy_kr?: string, courtesy_cn?: string, namu_title?: string, faction: string, tier: 0|1|2|3, role?: string }} Character */

/** @type {Character[]} */
export const TIER_0 = [
  // ── 위(魏) ──
  { name_kr: '조조', name_en: 'Cao Cao', name_cn: '曹操', courtesy_kr: '맹덕', courtesy_cn: '孟德', namu_title: '조조', faction: 'wei', tier: 0, role: '위 건국자, 최종보스' },
  { name_kr: '사마의', name_en: 'Sima Yi', name_cn: '司馬懿', courtesy_kr: '중달', courtesy_cn: '仲達', namu_title: '사마의', faction: 'wei', tier: 0, role: '위 중신 → 진 건국 기반' },
  { name_kr: '순욱', name_en: 'Xun Yu', name_cn: '荀彧', courtesy_kr: '문약', courtesy_cn: '文若', namu_title: '순욱', faction: 'wei', tier: 0, role: '조조의 왕좌창(王佐之才)' },
  { name_kr: '곽가', name_en: 'Guo Jia', name_cn: '郭嘉', courtesy_kr: '봉효', courtesy_cn: '奉孝', namu_title: '곽가', faction: 'wei', tier: 0, role: '조조 최측근 참모, 요절' },
  { name_kr: '하후돈', name_en: 'Xiahou Dun', name_cn: '夏侯惇', courtesy_kr: '원양', courtesy_cn: '元讓', namu_title: '하후돈', faction: 'wei', tier: 0, role: '조조 혈족 맹장' },
  { name_kr: '장료', name_en: 'Zhang Liao', name_cn: '張遼', courtesy_kr: '문원', courtesy_cn: '文遠', namu_title: '장료', faction: 'wei', tier: 0, role: '합비 수비, 오국 무쌍' },

  // ── 촉(蜀) ──
  { name_kr: '유비', name_en: 'Liu Bei', name_cn: '劉備', courtesy_kr: '현덕', courtesy_cn: '玄德', namu_title: '유비', faction: 'shu', tier: 0, role: '촉한 건국자, 주인공' },
  { name_kr: '관우', name_en: 'Guan Yu', name_cn: '關羽', courtesy_kr: '운장', courtesy_cn: '雲長', namu_title: '관우', faction: 'shu', tier: 0, role: '무성(武聖), 의리의 상징' },
  { name_kr: '장비', name_en: 'Zhang Fei', name_cn: '張飛', courtesy_kr: '익덕', courtesy_cn: '翼德', namu_title: '장비', faction: 'shu', tier: 0, role: '용맹, 장판교의 사나이' },
  { name_kr: '제갈량', name_en: 'Zhuge Liang', name_cn: '諸葛亮', courtesy_kr: '공명', courtesy_cn: '孔明', namu_title: '제갈량', faction: 'shu', tier: 0, role: '만능 참모, 삼고초려의 주인공' },
  { name_kr: '조운', name_en: 'Zhao Yun', name_cn: '趙雲', courtesy_kr: '자룡', courtesy_cn: '子龍', namu_title: '조운', faction: 'shu', tier: 0, role: '상산의 조자룡, 완벽한 장수' },

  // ── 오(吳) ──
  { name_kr: '손권', name_en: 'Sun Quan', name_cn: '孫權', courtesy_kr: '중모', courtesy_cn: '仲謀', namu_title: '손권', faction: 'wu', tier: 0, role: '오 건국자' },
  { name_kr: '주유', name_en: 'Zhou Yu', name_cn: '周瑜', courtesy_kr: '공근', courtesy_cn: '公瑾', namu_title: '주유(삼국지)', faction: 'wu', tier: 0, role: '적벽대전의 총사령관' },
  { name_kr: '손견', name_en: 'Sun Jian', name_cn: '孫堅', courtesy_kr: '문대', courtesy_cn: '文臺', namu_title: '손견', faction: 'wu', tier: 0, role: '강동의 호랑이' },
  { name_kr: '손책', name_en: 'Sun Ce', name_cn: '孫策', courtesy_kr: '백부', courtesy_cn: '伯符', namu_title: '손책', faction: 'wu', tier: 0, role: '소패왕, 강동 정복' },

  // ── 기타 ──
  { name_kr: '여포', name_en: 'Lu Bu', name_cn: '呂布', courtesy_kr: '봉선', courtesy_cn: '奉先', namu_title: '여포', faction: 'other', tier: 0, role: '최강 무장, 배신의 아이콘' },
  { name_kr: '동탁', name_en: 'Dong Zhuo', name_cn: '董卓', courtesy_kr: '중영', courtesy_cn: '仲穎', namu_title: '동탁', faction: 'other', tier: 0, role: '폭군, 난세의 시작' },
  { name_kr: '초선', name_en: 'Diao Chan', name_cn: '貂蟬', namu_title: '초선', faction: 'other', tier: 0, role: '연의 4대 미녀, 연환계' },
  { name_kr: '원소', name_en: 'Yuan Shao', name_cn: '袁紹', courtesy_kr: '본초', courtesy_cn: '本初', namu_title: '원소', faction: 'other', tier: 0, role: '하북 맹주, 관도대전' },
  { name_kr: '가후', name_en: 'Jia Xu', name_cn: '賈詡', courtesy_kr: '문화', courtesy_cn: '文和', namu_title: '가후', faction: 'wei', tier: 0, role: '독사 참모, 생존의 귀재' },
];

/** @type {Character[]} */
export const TIER_1 = [
  // ── 위 ──
  { name_kr: '하후연', name_en: 'Xiahou Yuan', name_cn: '夏侯淵', courtesy_kr: '묘재', courtesy_cn: '妙才', namu_title: '하후연', faction: 'wei', tier: 1, role: '기동 전술 명장' },
  { name_kr: '장합', name_en: 'Zhang He', name_cn: '張郃', courtesy_kr: '준예', courtesy_cn: '儁乂', namu_title: '장합', faction: 'wei', tier: 1, role: '가정 전투 수훈' },
  { name_kr: '서황', name_en: 'Xu Huang', name_cn: '徐晃', courtesy_kr: '공명', courtesy_cn: '公明', namu_title: '서황', faction: 'wei', tier: 1, role: '번성 구원, 주아부 재현' },
  { name_kr: '악진', name_en: 'Yue Jin', name_cn: '樂進', courtesy_kr: '문겸', courtesy_cn: '文謙', namu_title: '악진', faction: 'wei', tier: 1, role: '선등 장수' },
  { name_kr: '우금', name_en: 'Yu Jin', name_cn: '于禁', courtesy_kr: '문칙', courtesy_cn: '文則', namu_title: '우금', faction: 'wei', tier: 1, role: '군율의 화신, 번성 항복' },
  { name_kr: '전위', name_en: 'Dian Wei', name_cn: '典韋', namu_title: '전위(삼국지)', faction: 'wei', tier: 1, role: '조조의 근위대장, 완성 전사' },
  { name_kr: '허저', name_en: 'Xu Chu', name_cn: '許褚', courtesy_kr: '중강', courtesy_cn: '仲康', namu_title: '허저', faction: 'wei', tier: 1, role: '호치(虎癡), 조조 호위' },
  { name_kr: '조인', name_en: 'Cao Ren', name_cn: '曹仁', courtesy_kr: '자효', courtesy_cn: '子孝', namu_title: '조인', faction: 'wei', tier: 1, role: '수비 전문, 번성' },
  { name_kr: '조비', name_en: 'Cao Pi', name_cn: '曹丕', courtesy_kr: '자환', courtesy_cn: '子桓', namu_title: '조비', faction: 'wei', tier: 1, role: '위 초대 황제' },
  { name_kr: '방덕', name_en: 'Pang De', name_cn: '龐德', courtesy_kr: '영명', courtesy_cn: '令明', namu_title: '방덕', faction: 'wei', tier: 1, role: '관우전 선봉, 충절' },
  { name_kr: '서서', name_en: 'Xu Shu', name_cn: '徐庶', courtesy_kr: '원직', courtesy_cn: '元直', namu_title: '서서', faction: 'wei', tier: 1, role: '촉→위 이적, 효자' },
  { name_kr: '종회', name_en: 'Zhong Hui', name_cn: '鍾會', courtesy_kr: '사계', courtesy_cn: '士季', namu_title: '종회', faction: 'wei', tier: 1, role: '촉한 멸망 주도' },
  { name_kr: '등애', name_en: 'Deng Ai', name_cn: '鄧艾', courtesy_kr: '사재', courtesy_cn: '士載', namu_title: '등애', faction: 'wei', tier: 1, role: '음평 기습, 촉한 멸망' },
  { name_kr: '순공달', name_en: 'Xun Gongda', name_cn: '荀攸', courtesy_kr: '공달', courtesy_cn: '公達', namu_title: '순유', faction: 'wei', tier: 1, role: '순욱 조카, 모사' },
  { name_kr: '문앙', name_en: 'Wen Yang', name_cn: '文鴦', namu_title: '문앙', faction: 'wei', tier: 1, role: '후기 맹장' },

  // ── 촉 ──
  { name_kr: '마초', name_en: 'Ma Chao', name_cn: '馬超', courtesy_kr: '맹기', courtesy_cn: '孟起', namu_title: '마초', faction: 'shu', tier: 1, role: '서량의 맹장, 오호대장군' },
  { name_kr: '황충', name_en: 'Huang Zhong', name_cn: '黃忠', courtesy_kr: '한승', courtesy_cn: '漢升', namu_title: '황충', faction: 'shu', tier: 1, role: '노익장, 정군산' },
  { name_kr: '위연', name_en: 'Wei Yan', name_cn: '魏延', courtesy_kr: '문장', courtesy_cn: '文長', namu_title: '위연', faction: 'shu', tier: 1, role: '맹장, 반골의 낙인' },
  { name_kr: '방통', name_en: 'Pang Tong', name_cn: '龐統', courtesy_kr: '사원', courtesy_cn: '士元', namu_title: '방통', faction: 'shu', tier: 1, role: '봉추, 낙봉파 전사' },
  { name_kr: '마량', name_en: 'Ma Liang', name_cn: '馬良', courtesy_kr: '계상', courtesy_cn: '季常', namu_title: '마량', faction: 'shu', tier: 1, role: '백미, 이릉 전사' },
  { name_kr: '마속', name_en: 'Ma Su', name_cn: '馬謖', courtesy_kr: '유상', courtesy_cn: '幼常', namu_title: '마속', faction: 'shu', tier: 1, role: '가정 참패, 읍참마속' },
  { name_kr: '법정', name_en: 'Fa Zheng', name_cn: '法正', courtesy_kr: '효직', courtesy_cn: '孝直', namu_title: '법정(삼국지)', faction: 'shu', tier: 1, role: '유비 입촉 공신' },
  { name_kr: '강유', name_en: 'Jiang Wei', name_cn: '姜維', courtesy_kr: '백약', courtesy_cn: '伯約', namu_title: '강유', faction: 'shu', tier: 1, role: '제갈량 후계, 9차 북벌' },
  { name_kr: '유선', name_en: 'Liu Shan', name_cn: '劉禪', courtesy_kr: '공사', courtesy_cn: '公嗣', namu_title: '유선(삼국지)', faction: 'shu', tier: 1, role: '촉한 2대 황제, 아두' },
  { name_kr: '관흥', name_en: 'Guan Xing', name_cn: '關興', namu_title: '관흥', faction: 'shu', tier: 1, role: '관우의 아들' },
  { name_kr: '장포', name_en: 'Zhang Bao', name_cn: '張苞', namu_title: '장포', faction: 'shu', tier: 1, role: '장비의 아들' },
  { name_kr: '이엄', name_en: 'Li Yan', name_cn: '李嚴', courtesy_kr: '정방', courtesy_cn: '正方', namu_title: '이엄(삼국지)', faction: 'shu', tier: 1, role: '유비 탁고, 제갈량과 갈등' },

  // ── 오 ──
  { name_kr: '노숙', name_en: 'Lu Su', name_cn: '魯肅', courtesy_kr: '자경', courtesy_cn: '子敬', namu_title: '노숙', faction: 'wu', tier: 1, role: '적벽 외교, 유비 연합 주도' },
  { name_kr: '여몽', name_en: 'Lu Meng', name_cn: '呂蒙', courtesy_kr: '자명', courtesy_cn: '子明', namu_title: '여몽', faction: 'wu', tier: 1, role: '오하아몽, 형주 탈환' },
  { name_kr: '육손', name_en: 'Lu Xun', name_cn: '陸遜', courtesy_kr: '백언', courtesy_cn: '伯言', namu_title: '육손', faction: 'wu', tier: 1, role: '이릉대전 승리' },
  { name_kr: '감녕', name_en: 'Gan Ning', name_cn: '甘寧', courtesy_kr: '흥패', courtesy_cn: '興霸', namu_title: '감녕', faction: 'wu', tier: 1, role: '수적→맹장, 백기기습' },
  { name_kr: '주태', name_en: 'Zhou Tai', name_cn: '周泰', courtesy_kr: '유평', courtesy_cn: '幼平', namu_title: '주태', faction: 'wu', tier: 1, role: '손권 근위, 흉터 장수' },
  { name_kr: '태사자', name_en: 'Taishi Ci', name_cn: '太史慈', courtesy_kr: '자의', courtesy_cn: '子義', namu_title: '태사자', faction: 'wu', tier: 1, role: '효자 장수, 손책과 일기토' },
  { name_kr: '황개', name_en: 'Huang Gai', name_cn: '黃蓋', courtesy_kr: '공복', courtesy_cn: '公覆', namu_title: '황개', faction: 'wu', tier: 1, role: '고육지계, 적벽 화공' },
  { name_kr: '감택', name_en: 'Kan Ze', name_cn: '闞澤', courtesy_kr: '덕윤', courtesy_cn: '德潤', namu_title: '감택', faction: 'wu', tier: 1, role: '항서 전달, 문인' },
  { name_kr: '대교', name_en: 'Da Qiao', name_cn: '大喬', namu_title: '대교(삼국지)', faction: 'wu', tier: 1, role: '손책의 부인' },
  { name_kr: '소교', name_en: 'Xiao Qiao', name_cn: '小喬', namu_title: '소교(삼국지)', faction: 'wu', tier: 1, role: '주유의 부인' },
  { name_kr: '손상향', name_en: 'Sun Shangxiang', name_cn: '孫尚香', namu_title: '손부인', faction: 'wu', tier: 1, role: '유비의 부인, 여장군' },

  // ── 기타 세력 ──
  { name_kr: '원술', name_en: 'Yuan Shu', name_cn: '袁術', courtesy_kr: '공로', courtesy_cn: '公路', namu_title: '원술', faction: 'other', tier: 1, role: '자칭 황제, 원소 형제' },
  { name_kr: '진궁', name_en: 'Chen Gong', name_cn: '陳宮', courtesy_kr: '공대', courtesy_cn: '公臺', namu_title: '진궁', faction: 'other', tier: 1, role: '여포의 참모' },
  { name_kr: '장각', name_en: 'Zhang Jiao', name_cn: '張角', namu_title: '장각', faction: 'other', tier: 1, role: '황건적 수장' },
  { name_kr: '이유', name_en: 'Li Ru', name_cn: '李儒', namu_title: '이유(삼국지)', faction: 'other', tier: 1, role: '동탁의 참모' },
  { name_kr: '유표', name_en: 'Liu Biao', name_cn: '劉表', courtesy_kr: '경승', courtesy_cn: '景升', namu_title: '유표', faction: 'other', tier: 1, role: '형주 목사' },
  { name_kr: '장수', name_en: 'Zhang Xiu', name_cn: '張繡', namu_title: '장수(삼국지)', faction: 'other', tier: 1, role: '완성 전투, 전위 살해' },
  { name_kr: '공손찬', name_en: 'Gongsun Zan', name_cn: '公孫瓚', courtesy_kr: '백규', courtesy_cn: '伯珪', namu_title: '공손찬', faction: 'other', tier: 1, role: '백마장군, 유비 초기 후원' },
  { name_kr: '맹획', name_en: 'Meng Huo', name_cn: '孟獲', namu_title: '맹획', faction: 'other', tier: 1, role: '남만왕, 칠종칠금' },
  { name_kr: '장송', name_en: 'Zhang Song', name_cn: '張松', courtesy_kr: '영년', courtesy_cn: '永年', namu_title: '장송', faction: 'other', tier: 1, role: '유비 입촉 내응' },
  { name_kr: '화타', name_en: 'Hua Tuo', name_cn: '華佗', courtesy_kr: '원화', courtesy_cn: '元化', namu_title: '화타', faction: 'other', tier: 1, role: '신의(神醫)' },
  { name_kr: '여포의 딸', name_en: 'Lu Lingqi', name_cn: '呂玲綺', namu_title: '여씨(삼국지)', faction: 'other', tier: 1, role: '여포의 딸 (창작)' },
  { name_kr: '축융', name_en: 'Zhu Rong', name_cn: '祝融', namu_title: '축융부인', faction: 'other', tier: 1, role: '남만 여장수' },
  { name_kr: '안량', name_en: 'Yan Liang', name_cn: '顏良', namu_title: '안량', faction: 'other', tier: 1, role: '원소 맹장, 관우에게 참수' },
  { name_kr: '문추', name_en: 'Wen Chou', name_cn: '文醜', namu_title: '문추', faction: 'other', tier: 1, role: '원소 맹장' },
  { name_kr: '조홍', name_en: 'Cao Hong', name_cn: '曹洪', courtesy_kr: '자렴', courtesy_cn: '子廉', namu_title: '조홍', faction: 'wei', tier: 1, role: '조조 혈족 장수' },
];

/** @type {Character[]} */
export const TIER_2 = [
  // ── 위(魏) ──
  { name_kr: '가규', name_en: 'Jia Kui', name_cn: '賈逵', courtesy_kr: '양도', courtesy_cn: '梁道', namu_title: '가규', faction: 'wei', tier: 2, role: '위 행정관, 장수 겸비' },
  { name_kr: '곽회', name_en: 'Guo Huai', name_cn: '郭淮', courtesy_kr: '백제', courtesy_cn: '伯濟', namu_title: '곽회', faction: 'wei', tier: 2, role: '옹량 방어, 강유 상대' },
  { name_kr: '만총', name_en: 'Man Chong', name_cn: '滿寵', courtesy_kr: '백녕', courtesy_cn: '伯寧', namu_title: '만총', faction: 'wei', tier: 2, role: '합비 수비, 법관' },
  { name_kr: '조진', name_en: 'Cao Zhen', name_cn: '曹真', courtesy_kr: '자단', courtesy_cn: '子丹', namu_title: '조진', faction: 'wei', tier: 2, role: '대장군, 제갈량 방어' },
  { name_kr: '조예', name_en: 'Cao Rui', name_cn: '曹叡', courtesy_kr: '원중', courtesy_cn: '元仲', namu_title: '조예', faction: 'wei', tier: 2, role: '위 2대 황제, 명제' },
  { name_kr: '진태', name_en: 'Chen Tai', name_cn: '陳泰', courtesy_kr: '현백', courtesy_cn: '玄伯', namu_title: '진태', faction: 'wei', tier: 2, role: '강유 방어, 명장' },
  { name_kr: '학소', name_en: 'Hao Zhao', name_cn: '郝昭', courtesy_kr: '백도', courtesy_cn: '伯道', namu_title: '학소', faction: 'wei', tier: 2, role: '진창 수비, 제갈량 저지' },
  { name_kr: '문빙', name_en: 'Wen Pin', name_cn: '文聘', courtesy_kr: '중업', courtesy_cn: '仲業', namu_title: '문빙', faction: 'wei', tier: 2, role: '형주→위, 장강 수비' },
  { name_kr: '정욱', name_en: 'Cheng Yu', name_cn: '程昱', courtesy_kr: '중덕', courtesy_cn: '仲德', namu_title: '정욱', faction: 'wei', tier: 2, role: '조조 초기 참모' },
  { name_kr: '순유', name_en: 'Xun You', name_cn: '荀攸', courtesy_kr: '공달', courtesy_cn: '公達', namu_title: '순유', faction: 'wei', tier: 2, role: '순욱 조카, 군략가' },
  { name_kr: '종요', name_en: 'Zhong Yao', name_cn: '鍾繇', courtesy_kr: '원상', courtesy_cn: '元常', namu_title: '종요', faction: 'wei', tier: 2, role: '서예 명가, 관중 진무' },
  { name_kr: '사마사', name_en: 'Sima Shi', name_cn: '司馬師', courtesy_kr: '자원', courtesy_cn: '子元', namu_title: '사마사', faction: 'wei', tier: 2, role: '사마의 장남, 위 실권 장악' },
  { name_kr: '사마소', name_en: 'Sima Zhao', name_cn: '司馬昭', courtesy_kr: '자상', courtesy_cn: '子上', namu_title: '사마소', faction: 'wei', tier: 2, role: '사마의 차남, 진 건국 기반' },
  { name_kr: '사마염', name_en: 'Sima Yan', name_cn: '司馬炎', courtesy_kr: '안세', courtesy_cn: '安世', namu_title: '사마염', faction: 'wei', tier: 2, role: '진 무제, 삼국 통일' },
  { name_kr: '제갈탄', name_en: 'Zhuge Dan', name_cn: '諸葛誕', courtesy_kr: '공휴', courtesy_cn: '公休', namu_title: '제갈탄', faction: 'wei', tier: 2, role: '제갈량 일족, 회남 거병' },
  { name_kr: '하후패', name_en: 'Xiahou Ba', name_cn: '夏侯霸', namu_title: '하후패', faction: 'wei', tier: 2, role: '위→촉 투항, 하후연 아들' },
  { name_kr: '견초', name_en: 'Qian Zhao', name_cn: '牽招', courtesy_kr: '자경', courtesy_cn: '子經', namu_title: '견초', faction: 'wei', tier: 2, role: '위 변경 수비' },
  { name_kr: '나헌', name_en: 'Luo Xian', name_cn: '羅憲', courtesy_kr: '영칙', courtesy_cn: '令則', namu_title: '나헌', faction: 'wei', tier: 2, role: '영안 수비, 촉→위→진' },

  // ── 촉(蜀) ──
  { name_kr: '마대', name_en: 'Ma Dai', name_cn: '馬岱', namu_title: '마대', faction: 'shu', tier: 2, role: '마초 사촌, 위연 참수' },
  { name_kr: '마등', name_en: 'Ma Teng', name_cn: '馬騰', courtesy_kr: '수성', courtesy_cn: '壽成', namu_title: '마등', faction: 'shu', tier: 2, role: '마초의 아버지, 서량 군벌' },
  { name_kr: '왕평', name_en: 'Wang Ping', name_cn: '王平', courtesy_kr: '자균', courtesy_cn: '子均', namu_title: '왕평', faction: 'shu', tier: 2, role: '가정 구원, 한중 수비' },
  { name_kr: '등지', name_en: 'Deng Zhi', name_cn: '鄧芝', courtesy_kr: '백묘', courtesy_cn: '伯苗', namu_title: '등지', faction: 'shu', tier: 2, role: '오촉 동맹 외교관' },
  { name_kr: '장완', name_en: 'Jiang Wan', name_cn: '蔣琬', courtesy_kr: '공엄', courtesy_cn: '公琰', namu_title: '장완', faction: 'shu', tier: 2, role: '제갈량 후임 승상' },
  { name_kr: '비의', name_en: 'Fei Yi', name_cn: '費禕', courtesy_kr: '문위', courtesy_cn: '文偉', namu_title: '비의', faction: 'shu', tier: 2, role: '촉한 후기 재상' },
  { name_kr: '관평', name_en: 'Guan Ping', name_cn: '關平', namu_title: '관평', faction: 'shu', tier: 2, role: '관우의 양아들' },
  { name_kr: '곽익', name_en: 'Huo Yi', name_cn: '霍弋', namu_title: '곽익', faction: 'shu', tier: 2, role: '남중 도독, 충절' },
  { name_kr: '맹달', name_en: 'Meng Da', name_cn: '孟達', courtesy_kr: '자경', courtesy_cn: '子敬', namu_title: '맹달', faction: 'shu', tier: 2, role: '배반 3국 이적' },
  { name_kr: '곽준', name_en: 'Huo Jun', name_cn: '霍峻', courtesy_kr: '중막', courtesy_cn: '仲邈', namu_title: '곽준', faction: 'shu', tier: 2, role: '가맹관 수비' },

  // ── 오(吳) ──
  { name_kr: '육항', name_en: 'Lu Kang', name_cn: '陸抗', courtesy_kr: '유절', courtesy_cn: '幼節', namu_title: '육항', faction: 'wu', tier: 2, role: '육손의 아들, 오 최후의 명장' },
  { name_kr: '정보', name_en: 'Cheng Pu', name_cn: '程普', courtesy_kr: '덕모', courtesy_cn: '德謀', namu_title: '정보', faction: 'wu', tier: 2, role: '오 원로 장수, 적벽 참전' },
  { name_kr: '서성', name_en: 'Xu Sheng', name_cn: '徐盛', courtesy_kr: '문향', courtesy_cn: '文嚮', namu_title: '서성', faction: 'wu', tier: 2, role: '오 장수, 가성 전술' },
  { name_kr: '정봉', name_en: 'Ding Feng', name_cn: '丁奉', courtesy_kr: '승연', courtesy_cn: '承淵', namu_title: '정봉', faction: 'wu', tier: 2, role: '설중기습, 오 후기 명장' },
  { name_kr: '낙통', name_en: 'Luo Tong', name_cn: '駱統', courtesy_kr: '공서', courtesy_cn: '公緒', namu_title: '낙통', faction: 'wu', tier: 2, role: '오 행정관' },
  { name_kr: '주환', name_en: 'Zhu Huan', name_cn: '朱桓', courtesy_kr: '휴목', courtesy_cn: '休穆', namu_title: '주환', faction: 'wu', tier: 2, role: '오 수비 명장' },

  // ── 기타 ──
  { name_kr: '양호', name_en: 'Yang Hu', name_cn: '羊祜', courtesy_kr: '숙자', courtesy_cn: '叔子', namu_title: '양호', faction: 'other', tier: 2, role: '진 장수, 육항과 대치' },
  { name_kr: '두예', name_en: 'Du Yu', name_cn: '杜預', courtesy_kr: '원개', courtesy_cn: '元凱', namu_title: '두예', faction: 'other', tier: 2, role: '진 장수, 오 정벌 완성' },
  { name_kr: '노식', name_en: 'Lu Zhi', name_cn: '盧植', courtesy_kr: '자간', courtesy_cn: '子幹', namu_title: '노식', faction: 'other', tier: 2, role: '유비·공손찬의 스승' },
  { name_kr: '장임', name_en: 'Zhang Ren', name_cn: '張任', namu_title: '장임', faction: 'other', tier: 2, role: '유장 충신, 낙성 전투' },
  { name_kr: '한수', name_en: 'Han Sui', name_cn: '韓遂', courtesy_kr: '문약', courtesy_cn: '文約', namu_title: '한수', faction: 'other', tier: 2, role: '서량 군벌, 마등 맹우' },
  { name_kr: '황보숭', name_en: 'Huangfu Song', name_cn: '皇甫嵩', courtesy_kr: '의진', courtesy_cn: '義真', namu_title: '황보숭', faction: 'other', tier: 2, role: '황건적 토벌 명장' },
  { name_kr: '황월영', name_en: 'Huang Yueying', name_cn: '黃月英', namu_title: '황월영', faction: 'shu', tier: 2, role: '제갈량의 부인 (창작 확대)' },
  { name_kr: '관색', name_en: 'Guan Suo', name_cn: '關索', namu_title: '관색', faction: 'shu', tier: 2, role: '관우 아들 (창작)' },
];

/** @type {Character[]} */
export const TIER_3 = [
  // ── 위(魏) ──
  { name_kr: '견씨', name_en: 'Lady Zhen', name_cn: '', faction: 'wei', tier: 3 },
  { name_kr: '견홍', name_en: 'Qian Hong', name_cn: '牽弘', faction: 'wei', tier: 3 },
  { name_kr: '곽혁', name_en: 'Guo Yi', name_cn: '郭奕', faction: 'wei', tier: 3 },
  { name_kr: '관구검', name_en: 'Guanqiu Jian', name_cn: '', faction: 'wei', tier: 3 },
  { name_kr: '대릉', name_en: 'Dai Ling', name_cn: '戴陵', faction: 'wei', tier: 3 },
  { name_kr: '동소', name_en: 'Dong Zhao', name_cn: '董昭', faction: 'wei', tier: 3 },
  { name_kr: '모개', name_en: 'Mao Jie', name_cn: '毛玠', faction: 'wei', tier: 3 },
  { name_kr: '문흠', name_en: 'Wen Qin', name_cn: '文欽', faction: 'wei', tier: 3 },
  { name_kr: '부손', name_en: 'Fu Xun', name_cn: '傅巽', faction: 'wei', tier: 3 },
  { name_kr: '비요', name_en: 'Fei Yao', name_cn: '費耀', faction: 'wei', tier: 3 },
  { name_kr: '사마랑', name_en: 'Sima Lang', name_cn: '司馬朗', faction: 'wei', tier: 3 },
  { name_kr: '사마부', name_en: 'Sima Fu', name_cn: '司馬孚', faction: 'wei', tier: 3 },
  { name_kr: '서막', name_en: 'Xu Miao', name_cn: '徐邈', faction: 'wei', tier: 3 },
  { name_kr: '손례', name_en: 'Sun Li', name_cn: '孫礼', faction: 'wei', tier: 3 },
  { name_kr: '순심', name_en: 'Xun Chen', name_cn: '荀諶', faction: 'wei', tier: 3 },
  { name_kr: '신비', name_en: 'Xin Pi', name_cn: '辛毘', faction: 'wei', tier: 3 },
  { name_kr: '악취', name_en: 'Yue Jiu', name_cn: '楽就', faction: 'wei', tier: 3 },
  { name_kr: '양부', name_en: 'Yang Fu', name_cn: '楊阜', faction: 'wei', tier: 3 },
  { name_kr: '양서', name_en: 'Liang Xu', name_cn: '梁緒', faction: 'wei', tier: 3 },
  { name_kr: '양수', name_en: 'Yang Xiu', name_cn: '楊修', faction: 'wei', tier: 3 },
  { name_kr: '양습', name_en: 'Liang Xi', name_cn: '梁習', faction: 'wei', tier: 3 },
  { name_kr: '양흥', name_en: 'Liang Xing', name_cn: '梁興', faction: 'wei', tier: 3 },
  { name_kr: '여건', name_en: 'Lv Qian', name_cn: '呂虔', faction: 'wei', tier: 3 },
  { name_kr: '온회', name_en: 'Wen Hui', name_cn: '温恢', faction: 'wei', tier: 3 },
  { name_kr: '왕랑', name_en: 'Wang Lang', name_cn: '王朗', faction: 'wei', tier: 3 },
  { name_kr: '왕릉', name_en: 'Wang Ling', name_cn: '王凌', faction: 'wei', tier: 3 },
  { name_kr: '왕숙', name_en: 'Wang Su', name_cn: '王肅', faction: 'wei', tier: 3 },
  { name_kr: '왕쌍', name_en: 'Wang Shuang', name_cn: '王双', faction: 'wei', tier: 3 },
  { name_kr: '왕준', name_en: 'Wang Jun', name_cn: '王濬', faction: 'wei', tier: 3 },
  { name_kr: '왕찬', name_en: 'Wang Can', name_cn: '王粲', faction: 'wei', tier: 3 },
  { name_kr: '왕창', name_en: 'Wang Chang', name_cn: '王昶', faction: 'wei', tier: 3 },
  { name_kr: '위관', name_en: 'Wei Guan', name_cn: '衛瓘', faction: 'wei', tier: 3 },
  { name_kr: '유복', name_en: 'Liu Fu', name_cn: '劉馥', faction: 'wei', tier: 3 },
  { name_kr: '유엽', name_en: 'Liu Ye', name_cn: '劉曄', faction: 'wei', tier: 3 },
  { name_kr: '이전', name_en: 'Li Dian', name_cn: '李典', faction: 'wei', tier: 3 },
  { name_kr: '이통', name_en: 'Li Tong', name_cn: '李通', faction: 'wei', tier: 3 },
  { name_kr: '이풍', name_en: 'Li Feng', name_cn: '李豊', faction: 'wei', tier: 3 },
  { name_kr: '장간', name_en: 'Jiang Gan', name_cn: '蒋幹', faction: 'wei', tier: 3 },
  { name_kr: '장기', name_en: 'Zhang Ji', name_cn: '張既', faction: 'wei', tier: 3 },
  { name_kr: '장패', name_en: 'Zang Ba', name_cn: '臧覇', faction: 'wei', tier: 3 },
  { name_kr: '전예', name_en: 'Tian Yu', name_cn: '田豫', faction: 'wei', tier: 3 },
  { name_kr: '조순', name_en: 'Cao Chun', name_cn: '曹純', faction: 'wei', tier: 3 },
  { name_kr: '조식', name_en: 'Cao Zhi', name_cn: '曹植', faction: 'wei', tier: 3 },
  { name_kr: '조앙', name_en: 'Cao Ang', name_cn: '曹昂', faction: 'wei', tier: 3 },
  { name_kr: '조창', name_en: 'Cao Zhang', name_cn: '曹彰', faction: 'wei', tier: 3 },
  { name_kr: '조충', name_en: 'Cao Chong', name_cn: '曹沖', faction: 'wei', tier: 3 },
  { name_kr: '조휴', name_en: 'Cao Xiu', name_cn: '曹休', faction: 'wei', tier: 3 },
  { name_kr: '주령', name_en: 'Zhu Ling', name_cn: '朱霊', faction: 'wei', tier: 3 },
  { name_kr: '진교', name_en: 'Chen Jiao', name_cn: '陳矯', faction: 'wei', tier: 3 },
  { name_kr: '진군', name_en: 'Chen Qun', name_cn: '陳羣', faction: 'wei', tier: 3 },
  { name_kr: '진랑', name_en: 'Qin Lang', name_cn: '秦朗', faction: 'wei', tier: 3 },
  { name_kr: '진림', name_en: 'Chen Lin', name_cn: '陳琳', faction: 'wei', tier: 3 },
  { name_kr: '채모', name_en: 'Cai Mao', name_cn: '蔡瑁', faction: 'wei', tier: 3 },
  { name_kr: '채중', name_en: 'Cai Zhong', name_cn: '蔡中', faction: 'wei', tier: 3 },
  { name_kr: '채화', name_en: 'Cai He', name_cn: '蔡和', faction: 'wei', tier: 3 },
  { name_kr: '하안', name_en: 'He Yan', name_cn: '何晏', faction: 'wei', tier: 3 },
  { name_kr: '하후덕', name_en: 'Xiahou De', name_cn: '夏侯徳', faction: 'wei', tier: 3 },
  { name_kr: '하후무', name_en: 'Xiahou Mao', name_cn: '夏侯楙', faction: 'wei', tier: 3 },
  { name_kr: '하후상', name_en: 'Xiahou Shang', name_cn: '夏侯尚', faction: 'wei', tier: 3 },
  { name_kr: '하후위', name_en: 'Xiahou Wei', name_cn: '夏侯威', faction: 'wei', tier: 3 },
  { name_kr: '하후은', name_en: 'Xiahou En', name_cn: '夏侯恩', faction: 'wei', tier: 3 },
  { name_kr: '하후현', name_en: 'Xiahou Xuan', name_cn: '夏侯玄', faction: 'wei', tier: 3 },
  { name_kr: '하후혜', name_en: 'Xiahou Hui', name_cn: '夏侯恵', faction: 'wei', tier: 3 },
  { name_kr: '하후화', name_en: 'Xiahou He', name_cn: '夏侯和', faction: 'wei', tier: 3 },
  { name_kr: '한호', name_en: 'Han Hao', name_cn: '韓浩', faction: 'wei', tier: 3 },
  { name_kr: '화흠', name_en: 'Hua Xin', name_cn: '華歆', faction: 'wei', tier: 3 },
  { name_kr: '환계', name_en: 'Huan Jie', name_cn: '桓階', faction: 'wei', tier: 3 },
  { name_kr: '희지재', name_en: 'Xi Zhicai', name_cn: '戯志才', faction: 'wei', tier: 3 },
  // ── 촉(蜀) ──
  { name_kr: '간옹', name_en: 'Jian Yong', name_cn: '簡雍', faction: 'shu', tier: 3 },
  { name_kr: '고상', name_en: 'Gao Xiang', name_cn: '高翔', faction: 'shu', tier: 3 },
  { name_kr: '곽유지', name_en: 'Guo Youzhi', name_cn: '郭攸之', faction: 'shu', tier: 3 },
  { name_kr: '관이', name_en: 'Guan Yi', name_cn: '関彝', faction: 'shu', tier: 3 },
  { name_kr: '관정', name_en: 'Guan Jing', name_cn: '関靖', faction: 'shu', tier: 3 },
  { name_kr: '관통', name_en: 'Guan Tong', name_cn: '関統', faction: 'shu', tier: 3 },
  { name_kr: '극정', name_en: 'Xi Zheng', name_cn: '郤正', faction: 'shu', tier: 3 },
  { name_kr: '냉포', name_en: 'Leng Bao', name_cn: '冷苞', faction: 'shu', tier: 3 },
  { name_kr: '녕수', name_en: 'Ning Sui', name_cn: '寗随', faction: 'shu', tier: 3 },
  { name_kr: '뇌동', name_en: 'Lei Tong', name_cn: '雷銅', faction: 'shu', tier: 3 },
  { name_kr: '동윤', name_en: 'Dong Yun', name_cn: '董允', faction: 'shu', tier: 3 },
  { name_kr: '동화', name_en: 'Dong He', name_cn: '董和', faction: 'shu', tier: 3 },
  { name_kr: '등현', name_en: 'Deng Xian', name_cn: '鄧賢', faction: 'shu', tier: 3 },
  { name_kr: '마준', name_en: 'Ma Jun', name_cn: '馬遵', faction: 'shu', tier: 3 },
  { name_kr: '마철', name_en: 'Ma Tie', name_cn: '馬鉄', faction: 'shu', tier: 3 },
  { name_kr: '마충', name_en: 'Ma Zhong', name_cn: '馬忠', faction: 'shu', tier: 3 },
  { name_kr: '마휴', name_en: 'Ma Xiu', name_cn: '馬休', faction: 'shu', tier: 3 },
  { name_kr: '미방', name_en: 'Mi Fang', name_cn: '糜芳', faction: 'shu', tier: 3 },
  { name_kr: '미축', name_en: 'Mi Zhu', name_cn: '糜竺', faction: 'shu', tier: 3 },
  { name_kr: '부첨', name_en: 'Fu Qian', name_cn: '傅僉', faction: 'shu', tier: 3 },
  { name_kr: '비시', name_en: 'Fei Shi', name_cn: '費詩', faction: 'shu', tier: 3 },
  { name_kr: '손건', name_en: 'Sun Qian', name_cn: '孫乾', faction: 'shu', tier: 3 },
  { name_kr: '양의', name_en: 'Yang Yi', name_cn: '楊儀', faction: 'shu', tier: 3 },
  { name_kr: '양홍', name_en: 'Yang Hong', name_cn: '楊弘', faction: 'shu', tier: 3 },
  { name_kr: '엄안', name_en: 'Yan Yan', name_cn: '厳顔', faction: 'shu', tier: 3 },
  { name_kr: '여개', name_en: 'Lv Kai', name_cn: '呂凱', faction: 'shu', tier: 3 },
  { name_kr: '오란', name_en: 'Wu Lan', name_cn: '呉蘭', faction: 'shu', tier: 3 },
  { name_kr: '오반', name_en: 'Wu Ban', name_cn: '呉班', faction: 'shu', tier: 3 },
  { name_kr: '오의', name_en: 'Wu Yi', name_cn: '呉懿', faction: 'shu', tier: 3 },
  { name_kr: '왕문', name_en: 'Wang Men', name_cn: '王門', faction: 'shu', tier: 3 },
  { name_kr: '왕보', name_en: 'Wang Fu', name_cn: '王甫', faction: 'shu', tier: 3 },
  { name_kr: '왕수', name_en: 'Wang Xiu', name_cn: '王修', faction: 'shu', tier: 3 },
  { name_kr: '왕항', name_en: 'Wang Kang', name_cn: '王伉', faction: 'shu', tier: 3 },
  { name_kr: '요화', name_en: 'Liao Hua', name_cn: '廖化', faction: 'shu', tier: 3 },
  { name_kr: '위유', name_en: 'Wei You', name_cn: '魏攸', faction: 'shu', tier: 3 },
  { name_kr: '유기', name_en: 'Liu Qi', name_cn: '劉琦', faction: 'shu', tier: 3 },
  { name_kr: '유봉', name_en: 'Liu Feng', name_cn: '劉封', faction: 'shu', tier: 3 },
  { name_kr: '유순', name_en: 'Liu Xun', name_cn: '劉循', faction: 'shu', tier: 3 },
  { name_kr: '유심', name_en: 'Liu Chen', name_cn: '劉諶', faction: 'shu', tier: 3 },
  { name_kr: '유우', name_en: 'Liu Yu', name_cn: '劉虞', faction: 'shu', tier: 3 },
  { name_kr: '유파', name_en: 'Liu Ba', name_cn: '劉巴', faction: 'shu', tier: 3 },
  { name_kr: '윤묵', name_en: 'Yin Mo', name_cn: '尹黙', faction: 'shu', tier: 3 },
  { name_kr: '이적', name_en: 'Li Ji', name_cn: '伊籍', faction: 'shu', tier: 3 },
  { name_kr: '이회', name_en: 'Li Hui', name_cn: '李恢', faction: 'shu', tier: 3 },
  { name_kr: '장익', name_en: 'Zhang Yi', name_cn: '張翼', faction: 'shu', tier: 3 },
  { name_kr: '제갈균', name_en: 'Zhuge Jun', name_cn: '諸葛均', faction: 'shu', tier: 3 },
  { name_kr: '조루', name_en: 'Zhao Lei', name_cn: '趙累', faction: 'shu', tier: 3 },
  { name_kr: '주창', name_en: 'Zhou Cang', name_cn: '周倉', faction: 'shu', tier: 3 },
  { name_kr: '진도', name_en: 'Chen Dao', name_cn: '陳到', faction: 'shu', tier: 3 },
  { name_kr: '진복', name_en: 'Qin Mi', name_cn: '秦宓', faction: 'shu', tier: 3 },
  { name_kr: '진식', name_en: 'Chen Shi', name_cn: '陳式', faction: 'shu', tier: 3 },
  { name_kr: '진진', name_en: 'Chen Zhen', name_cn: '陳震', faction: 'shu', tier: 3 },
  { name_kr: '초주', name_en: 'Qiao Zhou', name_cn: '譙周', faction: 'shu', tier: 3 },
  { name_kr: '풍습', name_en: 'Feng Xi', name_cn: '馮習', faction: 'shu', tier: 3 },
  { name_kr: '향랑', name_en: 'Xiang Lang', name_cn: '向朗', faction: 'shu', tier: 3 },
  { name_kr: '향총', name_en: 'Xiang Chong', name_cn: '向寵', faction: 'shu', tier: 3 },
  { name_kr: '호반', name_en: 'Hu Ban', name_cn: '胡班', faction: 'shu', tier: 3 },
  { name_kr: '황권', name_en: 'Huang Quan', name_cn: '黄権', faction: 'shu', tier: 3 },
  // ── 오(吳) ──
  { name_kr: '가범', name_en: 'Jia Fan', name_cn: '賈範', faction: 'wu', tier: 3 },
  { name_kr: '가화', name_en: 'Jia Hua', name_cn: '賈華', faction: 'wu', tier: 3 },
  { name_kr: '고담', name_en: 'Gu Tan', name_cn: '顧譚', faction: 'wu', tier: 3 },
  { name_kr: '고옹', name_en: 'Gu Yong', name_cn: '顧雍', faction: 'wu', tier: 3 },
  { name_kr: '능조', name_en: 'Ling Cao', name_cn: '凌操', faction: 'wu', tier: 3 },
  { name_kr: '능통', name_en: 'Ling Tong', name_cn: '凌統', faction: 'wu', tier: 3 },
  { name_kr: '동습', name_en: 'Dong Xi', name_cn: '董襲', faction: 'wu', tier: 3 },
  { name_kr: '반장', name_en: 'Pan Zhang', name_cn: '潘璋', faction: 'wu', tier: 3 },
  { name_kr: '반준', name_en: 'Pan Jun', name_cn: '潘濬', faction: 'wu', tier: 3 },
  { name_kr: '보즐', name_en: 'Bu Zhi', name_cn: '歩騭', faction: 'wu', tier: 3 },
  { name_kr: '설종', name_en: 'Xue Zong', name_cn: '薛綜', faction: 'wu', tier: 3 },
  { name_kr: '소비', name_en: 'Su Fei', name_cn: '蘇飛', faction: 'wu', tier: 3 },
  { name_kr: '손교', name_en: 'Sun Jiao', name_cn: '孫皎', faction: 'wu', tier: 3 },
  { name_kr: '손등', name_en: 'Sun Deng', name_cn: '孫登', faction: 'wu', tier: 3 },
  { name_kr: '손소', name_en: 'Sun Shao', name_cn: '孫韶', faction: 'wu', tier: 3 },
  { name_kr: '손유', name_en: 'Sun You', name_cn: '孫瑜', faction: 'wu', tier: 3 },
  { name_kr: '손익', name_en: 'Sun Yi', name_cn: '孫翊', faction: 'wu', tier: 3 },
  { name_kr: '손정', name_en: 'Sun Jing', name_cn: '孫静', faction: 'wu', tier: 3 },
  { name_kr: '손중', name_en: 'Sun Zhong', name_cn: '孫仲', faction: 'wu', tier: 3 },
  { name_kr: '손환', name_en: 'Sun Huan', name_cn: '孫桓', faction: 'wu', tier: 3 },
  { name_kr: '엄준', name_en: 'Yan Jun', name_cn: '厳畯', faction: 'wu', tier: 3 },
  { name_kr: '여대', name_en: 'Lv Dai', name_cn: '呂岱', faction: 'wu', tier: 3 },
  { name_kr: '여범', name_en: 'Lv Fan', name_cn: '呂範', faction: 'wu', tier: 3 },
  { name_kr: '여위황', name_en: 'Lv Weihuang', name_cn: '呂威璜', faction: 'wu', tier: 3 },
  { name_kr: '오경', name_en: 'Wu Jing', name_cn: '呉景', faction: 'wu', tier: 3 },
  { name_kr: '우번', name_en: 'Yu Fan', name_cn: '虞翻', faction: 'wu', tier: 3 },
  { name_kr: '육적', name_en: 'Lu Ji', name_cn: '陸績', faction: 'wu', tier: 3 },
  { name_kr: '장굉', name_en: 'Zhang Hong', name_cn: '張紘', faction: 'wu', tier: 3 },
  { name_kr: '장소', name_en: 'Zhang Zhao', name_cn: '張昭', faction: 'wu', tier: 3 },
  { name_kr: '장온', name_en: 'Zhang Wen', name_cn: '張温', faction: 'wu', tier: 3 },
  { name_kr: '장제', name_en: 'Zhang Ji', name_cn: '張悌', faction: 'wu', tier: 3 },
  { name_kr: '장흠', name_en: 'Jiang Qin', name_cn: '蔣欽', faction: 'wu', tier: 3 },
  { name_kr: '전종', name_en: 'Quan Cong', name_cn: '全琮', faction: 'wu', tier: 3 },
  { name_kr: '제갈각', name_en: 'Zhuge Ke', name_cn: '諸葛恪', faction: 'wu', tier: 3 },
  { name_kr: '제갈근', name_en: 'Zhuge Jin', name_cn: '諸葛謹', faction: 'wu', tier: 3 },
  { name_kr: '주거', name_en: 'Zhu Ju', name_cn: '朱據', faction: 'wu', tier: 3 },
  { name_kr: '주방', name_en: 'Zhou Fang', name_cn: '周魴', faction: 'wu', tier: 3 },
  { name_kr: '주연', name_en: 'Zhu Ran', name_cn: '朱然', faction: 'wu', tier: 3 },
  { name_kr: '주치', name_en: 'Zhu Zhi', name_cn: '朱治', faction: 'wu', tier: 3 },
  { name_kr: '진무', name_en: 'Chen Wu', name_cn: '陳武', faction: 'wu', tier: 3 },
  { name_kr: '진횡', name_en: 'Chen Heng', name_cn: '陳横', faction: 'wu', tier: 3 },
  { name_kr: '한당', name_en: 'Han Dang', name_cn: '韓当', faction: 'wu', tier: 3 },
  // ── 진(晉) ──
  { name_kr: '가충', name_en: 'Jia Chong', name_cn: '賈充', faction: 'jin', tier: 3 },
  { name_kr: '양조', name_en: 'Yang Zhao', name_cn: '楊肇', faction: 'jin', tier: 3 },
  { name_kr: '주지', name_en: 'Zhou Zhi', name_cn: '周旨', faction: 'jin', tier: 3 },
  // ── 기타 세력 ──
  { name_kr: '고간', name_en: 'Gao Gan', name_cn: '高幹', faction: 'other', tier: 3 },
  { name_kr: '고람', name_en: 'Gao Lan', name_cn: '高覧', faction: 'other', tier: 3 },
  { name_kr: '고순', name_en: 'Gao Shun', name_cn: '高順', faction: 'other', tier: 3 },
  { name_kr: '고승', name_en: 'Gao Sheng', name_cn: '高昇', faction: 'other', tier: 3 },
  { name_kr: '고유', name_en: 'Gao You', name_cn: '', faction: 'other', tier: 3 },
  { name_kr: '고정', name_en: 'Gao Ding', name_cn: '高定', faction: 'other', tier: 3 },
  { name_kr: '고패', name_en: 'Gao Pei', name_cn: '高沛', faction: 'other', tier: 3 },
  { name_kr: '공도', name_en: 'Gong Du', name_cn: '龔都', faction: 'other', tier: 3 },
  { name_kr: '공손강', name_en: 'Gongsun Kang', name_cn: '公孫康', faction: 'other', tier: 3 },
  { name_kr: '공손공', name_en: 'Gongsun Gong', name_cn: '公孫恭', faction: 'other', tier: 3 },
  { name_kr: '공손도', name_en: 'Gongsun Du', name_cn: '公孫度', faction: 'other', tier: 3 },
  { name_kr: '공손범', name_en: 'Gongsun Fan', name_cn: '公孫範', faction: 'other', tier: 3 },
  { name_kr: '공손속', name_en: 'Gongsun Xu', name_cn: '公孫続', faction: 'other', tier: 3 },
  { name_kr: '공손연', name_en: 'Gongsun Yuan', name_cn: '公孫淵', faction: 'other', tier: 3 },
  { name_kr: '공손월', name_en: 'Gongsun Yue', name_cn: '公孫越', faction: 'other', tier: 3 },
  { name_kr: '공융', name_en: 'Kong Rong', name_cn: '孔融', faction: 'other', tier: 3 },
  { name_kr: '공주', name_en: 'Kong Zhou', name_cn: '孔伷', faction: 'other', tier: 3 },
  { name_kr: '공지', name_en: 'Gong Zhi', name_cn: '鞏志', faction: 'other', tier: 3 },
  { name_kr: '곽도', name_en: 'Guo Tu', name_cn: '郭図', faction: 'other', tier: 3 },
  { name_kr: '곽마', name_en: 'Guo Ma', name_cn: '郭馬', faction: 'other', tier: 3 },
  { name_kr: '곽사', name_en: 'Guo Si', name_cn: '郭汜', faction: 'other', tier: 3 },
  { name_kr: '관해', name_en: 'Guan Hai', name_cn: '管亥', faction: 'other', tier: 3 },
  { name_kr: '괴량', name_en: 'Kuai Liang', name_cn: '蒯良', faction: 'other', tier: 3 },
  { name_kr: '괴월', name_en: 'Kuai Yue', name_cn: '蒯越', faction: 'other', tier: 3 },
  { name_kr: '교모', name_en: 'Qiao Mao', name_cn: '橋瑁', faction: 'other', tier: 3 },
  { name_kr: '구건', name_en: 'Qiu Jian', name_cn: '丘建', faction: 'other', tier: 3 },
  { name_kr: '구본', name_en: 'Qiu Ben', name_cn: '丘本', faction: 'other', tier: 3 },
  { name_kr: '구성', name_en: 'Qu Xing', name_cn: '区星', faction: 'other', tier: 3 },
  { name_kr: '국연', name_en: 'Guo Yuan', name_cn: '国淵', faction: 'other', tier: 3 },
  { name_kr: '국의', name_en: 'Guo Yi', name_cn: '', faction: 'other', tier: 3 },
  { name_kr: '금선', name_en: 'Jin Xuan', name_cn: '', faction: 'other', tier: 3 },
  { name_kr: '금의', name_en: 'Jin Yi', name_cn: '', faction: 'other', tier: 3 },
  { name_kr: '금환삼결', name_en: 'Jinhuansanjie', name_cn: '', faction: 'other', tier: 3 },
  { name_kr: '기령', name_en: 'Ji Ling', name_cn: '紀霊', faction: 'other', tier: 3 },
  { name_kr: '뇌박', name_en: 'Lei Bo', name_cn: '雷薄', faction: 'other', tier: 3 },
  { name_kr: '누규', name_en: 'Lou Gui', name_cn: '婁圭', faction: 'other', tier: 3 },
  { name_kr: '누현', name_en: 'Lou Xuan', name_cn: '楼玄', faction: 'other', tier: 3 },
  { name_kr: '단경', name_en: 'Dan Jing', name_cn: '単経', faction: 'other', tier: 3 },
  { name_kr: '담웅', name_en: 'Tan Xiong', name_cn: '譚雄', faction: 'other', tier: 3 },
  { name_kr: '대래동주', name_en: 'Dailaidongzhu', name_cn: '帯来洞主', faction: 'other', tier: 3 },
  { name_kr: '도겸', name_en: 'Tao Qian', name_cn: '陶謙', faction: 'other', tier: 3 },
  { name_kr: '동도나', name_en: 'Dongtuna', name_cn: '董荼那', faction: 'other', tier: 3 },
  { name_kr: '동민', name_en: 'Dong Min', name_cn: '董旻', faction: 'other', tier: 3 },
  { name_kr: '동승', name_en: 'Dong Cheng', name_cn: '董承', faction: 'other', tier: 3 },
  { name_kr: '등무', name_en: 'Deng Mao', name_cn: '鄧茂', faction: 'other', tier: 3 },
  { name_kr: '마완', name_en: 'Ma Wan', name_cn: '馬玩', faction: 'other', tier: 3 },
  { name_kr: '망아장', name_en: 'Mangyachang', name_cn: '忙牙長', faction: 'other', tier: 3 },
  { name_kr: '맹우', name_en: 'Meng You', name_cn: '孟優', faction: 'other', tier: 3 },
  { name_kr: '목록대왕', name_en: 'King Mulu', name_cn: '木鹿大王', faction: 'other', tier: 3 },
  { name_kr: '목순', name_en: 'Mu Shun', name_cn: '穆順', faction: 'other', tier: 3 },
  { name_kr: '무안국', name_en: 'Wu Anguo', name_cn: '武安国', faction: 'other', tier: 3 },
  { name_kr: '반봉', name_en: 'Pan Feng', name_cn: '潘鳳', faction: 'other', tier: 3 },
  { name_kr: '배원소', name_en: 'Pei Yuanshao', name_cn: '裴元紹', faction: 'other', tier: 3 },
  { name_kr: '번능', name_en: 'Fan Neng', name_cn: '樊能', faction: 'other', tier: 3 },
  { name_kr: '번조', name_en: 'Fan Chou', name_cn: '樊稠', faction: 'other', tier: 3 },
  { name_kr: '변희', name_en: 'Bian Xi', name_cn: '卞喜', faction: 'other', tier: 3 },
  { name_kr: '봉기', name_en: 'Feng Ji', name_cn: '逢紀', faction: 'other', tier: 3 },
  { name_kr: '부사인', name_en: 'Fu Shiren', name_cn: '傅士仁', faction: 'other', tier: 3 },
  { name_kr: '비연', name_en: 'Bei Yan', name_cn: '卑衍', faction: 'other', tier: 3 },
  { name_kr: '사마가', name_en: 'Shamoke', name_cn: '沙摩柯', faction: 'other', tier: 3 },
  { name_kr: '서영', name_en: 'Xu Rong', name_cn: '徐栄', faction: 'other', tier: 3 },
  { name_kr: '성공영', name_en: 'Chenggong Ying', name_cn: '成公英', faction: 'other', tier: 3 },
  { name_kr: '성의', name_en: 'Cheng Yi', name_cn: '成宜', faction: 'other', tier: 3 },
  { name_kr: '송헌', name_en: 'Song Xian', name_cn: '宋憲', faction: 'other', tier: 3 },
  { name_kr: '순우경', name_en: 'Chunyu Qiong', name_cn: '淳于瓊', faction: 'other', tier: 3 },
  { name_kr: '신의', name_en: 'Shen Yi', name_cn: '申儀', faction: 'other', tier: 3 },
  { name_kr: '신탐', name_en: 'Shen Dan', name_cn: '申耽', faction: 'other', tier: 3 },
  { name_kr: '신평', name_en: 'Xin Ping', name_cn: '辛評', faction: 'other', tier: 3 },
  { name_kr: '심배', name_en: 'Shen Pei', name_cn: '審配', faction: 'other', tier: 3 },
  { name_kr: '아회남', name_en: 'Ahuinan', name_cn: '阿会喃', faction: 'other', tier: 3 },
  { name_kr: '악환', name_en: 'E Huan', name_cn: '顎煥', faction: 'other', tier: 3 },
  { name_kr: '양백', name_en: 'Yang Bai', name_cn: '楊柏', faction: 'other', tier: 3 },
  { name_kr: '양봉', name_en: 'Yang Feng', name_cn: '楊鋒', faction: 'other', tier: 3 },
  { name_kr: '양송', name_en: 'Yang Song', name_cn: '楊松', faction: 'other', tier: 3 },
  { name_kr: '양앙', name_en: 'Yang Ang', name_cn: '楊昂', faction: 'other', tier: 3 },
  { name_kr: '양임', name_en: 'Yang Ren', name_cn: '楊任', faction: 'other', tier: 3 },
  { name_kr: '양추', name_en: 'Yang Qiu', name_cn: '楊秋', faction: 'other', tier: 3 },
  { name_kr: '양회', name_en: 'Yang Huai', name_cn: '楊懐', faction: 'other', tier: 3 },
  { name_kr: '엄강', name_en: 'Yan Gang', name_cn: '厳綱', faction: 'other', tier: 3 },
  { name_kr: '엄백호', name_en: 'Yan Baihu', name_cn: '厳白虎', faction: 'other', tier: 3 },
  { name_kr: '엄여', name_en: 'Yan Yu', name_cn: '厳輿', faction: 'other', tier: 3 },
  { name_kr: '엄정', name_en: 'Yan Zheng', name_cn: '厳政', faction: 'other', tier: 3 },
  { name_kr: '여광', name_en: 'Lv Kuang', name_cn: '呂曠', faction: 'other', tier: 3 },
  { name_kr: '여상', name_en: 'Lv Xiang', name_cn: '呂翔', faction: 'other', tier: 3 },
  { name_kr: '염상', name_en: 'Yan Xiang', name_cn: '閻象', faction: 'other', tier: 3 },
  { name_kr: '염유', name_en: 'Yan Rou', name_cn: '閻柔', faction: 'other', tier: 3 },
  { name_kr: '염포', name_en: 'Yan Pu', name_cn: '閻圃', faction: 'other', tier: 3 },
  { name_kr: '염행', name_en: 'Yan Xing', name_cn: '閻行', faction: 'other', tier: 3 },
  { name_kr: '올돌골', name_en: 'Wutugu', name_cn: '兀突骨', faction: 'other', tier: 3 },
  { name_kr: '옹개', name_en: 'Yong Kai', name_cn: '雍闓', faction: 'other', tier: 3 },
  { name_kr: '왕루', name_en: 'Wang Lei', name_cn: '王累', faction: 'other', tier: 3 },
  { name_kr: '왕위', name_en: 'Wang Wei', name_cn: '王威', faction: 'other', tier: 3 },
  { name_kr: '왕윤', name_en: 'Wang Yun', name_cn: '王允', faction: 'other', tier: 3 },
  { name_kr: '우보', name_en: 'Niu Fu', name_cn: '牛輔', faction: 'other', tier: 3 },
  { name_kr: '원담', name_en: 'Yuan Tan', name_cn: '袁譚', faction: 'other', tier: 3 },
  { name_kr: '원상', name_en: 'Yuan Shang', name_cn: '袁尚', faction: 'other', tier: 3 },
  { name_kr: '원윤', name_en: 'Yuan Yin', name_cn: '袁胤', faction: 'other', tier: 3 },
  { name_kr: '원희', name_en: 'Yuan Xi', name_cn: '袁熙', faction: 'other', tier: 3 },
  { name_kr: '위속', name_en: 'Wei Xu', name_cn: '魏続', faction: 'other', tier: 3 },
  { name_kr: '유도', name_en: 'Liu Du', name_cn: '劉度', faction: 'other', tier: 3 },
  { name_kr: '유반', name_en: 'Liu Pan', name_cn: '劉磐', faction: 'other', tier: 3 },
  { name_kr: '유섭', name_en: 'Yu She', name_cn: '兪渉', faction: 'other', tier: 3 },
  { name_kr: '유언', name_en: 'Liu Yan', name_cn: '劉焉', faction: 'other', tier: 3 },
  { name_kr: '유요', name_en: 'Liu Yao', name_cn: '劉繇', faction: 'other', tier: 3 },
  { name_kr: '유장', name_en: 'Liu Zhang', name_cn: '劉璋', faction: 'other', tier: 3 },
  { name_kr: '유종', name_en: 'Liu Cong', name_cn: '劉琮', faction: 'other', tier: 3 },
  { name_kr: '유현', name_en: 'Liu Xian', name_cn: '劉賢', faction: 'other', tier: 3 },
  { name_kr: '유훈', name_en: 'Liu Xun', name_cn: '劉勲', faction: 'other', tier: 3 },
  { name_kr: '윤상', name_en: 'Yin Shang', name_cn: '尹賞', faction: 'other', tier: 3 },
  { name_kr: '윤직', name_en: 'Lun Zhi', name_cn: '倫直', faction: 'other', tier: 3 },
  { name_kr: '이각', name_en: 'Li Jue', name_cn: '李搉', faction: 'other', tier: 3 },
  { name_kr: '이숙', name_en: 'Li Su', name_cn: '李粛', faction: 'other', tier: 3 },
  { name_kr: '이이', name_en: 'Li Yi', name_cn: '李異', faction: 'other', tier: 3 },
  { name_kr: '장개', name_en: 'Zhang Kai', name_cn: '張闓', faction: 'other', tier: 3 },
  { name_kr: '장량', name_en: 'Zhang Liang', name_cn: '張梁', faction: 'other', tier: 3 },
  { name_kr: '장로', name_en: 'Zhang Lu', name_cn: '張魯', faction: 'other', tier: 3 },
  { name_kr: '장막', name_en: 'Zhang Miao', name_cn: '張邈', faction: 'other', tier: 3 },
  { name_kr: '장만성', name_en: 'Zhang Mancheng', name_cn: '張曼成', faction: 'other', tier: 3 },
  { name_kr: '장보', name_en: 'Zhang Bao', name_cn: '張宝', faction: 'other', tier: 3 },
  { name_kr: '장양', name_en: 'Zhang Yang', name_cn: '張楊', faction: 'other', tier: 3 },
  { name_kr: '장연', name_en: 'Zhang Yan', name_cn: '張燕', faction: 'other', tier: 3 },
  { name_kr: '장위', name_en: 'Zhang Wei', name_cn: '張衛', faction: 'other', tier: 3 },
  { name_kr: '장윤', name_en: 'Zhang Yun', name_cn: '張允', faction: 'other', tier: 3 },
  { name_kr: '장의거', name_en: 'Jiang Yiqu', name_cn: '蒋義渠', faction: 'other', tier: 3 },
  { name_kr: '장횡', name_en: 'Zhang Heng', name_cn: '張横', faction: 'other', tier: 3 },
  { name_kr: '장훈', name_en: 'Zhang Xun', name_cn: '張勲', faction: 'other', tier: 3 },
  { name_kr: '저수', name_en: 'Ju Shou', name_cn: '沮授', faction: 'other', tier: 3 },
  { name_kr: '전주', name_en: 'Tian Chou', name_cn: '田疇', faction: 'other', tier: 3 },
  { name_kr: '전풍', name_en: 'Tian Feng', name_cn: '田豊', faction: 'other', tier: 3 },
  { name_kr: '전해', name_en: 'Tian Kai', name_cn: '田楷', faction: 'other', tier: 3 },
  { name_kr: '정원지', name_en: 'Cheng Yuanzhi', name_cn: '程遠志', faction: 'other', tier: 3 },
  { name_kr: '정은', name_en: 'Cheng Yin', name_cn: '程銀', faction: 'other', tier: 3 },
  { name_kr: '조무', name_en: 'Zu Mao', name_cn: '祖茂', faction: 'other', tier: 3 },
  { name_kr: '조범', name_en: 'Zhao Fan', name_cn: '趙範', faction: 'other', tier: 3 },
  { name_kr: '조성', name_en: 'Cao Xing', name_cn: '曹性', faction: 'other', tier: 3 },
  { name_kr: '조표', name_en: 'Cao Bao', name_cn: '曹豹', faction: 'other', tier: 3 },
  { name_kr: '주앙', name_en: 'Zhou Ang', name_cn: '周昂', faction: 'other', tier: 3 },
  { name_kr: '주준', name_en: 'Zhu Jun', name_cn: '朱儁', faction: 'other', tier: 3 },
  { name_kr: '주포', name_en: 'Zhu Bao', name_cn: '朱褒', faction: 'other', tier: 3 },
  { name_kr: '주흔', name_en: 'Zhou Xin', name_cn: '周昕', faction: 'other', tier: 3 },
  { name_kr: '진규', name_en: 'Chen Gui', name_cn: '陳珪', faction: 'other', tier: 3 },
  { name_kr: '진기', name_en: 'Chen Ji', name_cn: '陳紀', faction: 'other', tier: 3 },
  { name_kr: '진등', name_en: 'Chen Deng', name_cn: '陳登', faction: 'other', tier: 3 },
  { name_kr: '진란', name_en: 'Chen Lan', name_cn: '陳蘭', faction: 'other', tier: 3 },
  { name_kr: '진응', name_en: 'Chen Ying', name_cn: '陳応', faction: 'other', tier: 3 },
  { name_kr: '착융', name_en: 'Ze Rong', name_cn: '笮融', faction: 'other', tier: 3 },
  { name_kr: '추단', name_en: 'Chu Dan', name_cn: '雛丹', faction: 'other', tier: 3 },
  { name_kr: '타사대왕', name_en: 'King Duosi', name_cn: '朶思大王', faction: 'other', tier: 3 },
  { name_kr: '파재', name_en: 'Bo Cai', name_cn: '波才', faction: 'other', tier: 3 },
  { name_kr: '하의', name_en: 'He Yi', name_cn: '何儀', faction: 'other', tier: 3 },
  { name_kr: '하진', name_en: 'He Jin', name_cn: '何進', faction: 'other', tier: 3 },
  { name_kr: '학맹', name_en: 'Hao Meng', name_cn: '郝萌', faction: 'other', tier: 3 },
  { name_kr: '한덕', name_en: 'Han De', name_cn: '韓徳', faction: 'other', tier: 3 },
  { name_kr: '한복', name_en: 'Han Fu', name_cn: '韓馥', faction: 'other', tier: 3 },
  { name_kr: '한섬', name_en: 'Han Xian', name_cn: '韓暹', faction: 'other', tier: 3 },
  { name_kr: '한숭', name_en: 'Han Song', name_cn: '韓嵩', faction: 'other', tier: 3 },
  { name_kr: '한윤', name_en: 'Han Yin', name_cn: '韓胤', faction: 'other', tier: 3 },
  { name_kr: '한충', name_en: 'Han Zhong', name_cn: '韓忠', faction: 'other', tier: 3 },
  { name_kr: '한현', name_en: 'Han Xuan', name_cn: '韓玄', faction: 'other', tier: 3 },
  { name_kr: '허공', name_en: 'Xu Gong', name_cn: '許貢', faction: 'other', tier: 3 },
  { name_kr: '허유', name_en: 'Xu You', name_cn: '許攸', faction: 'other', tier: 3 },
  { name_kr: '허정', name_en: 'Xu Jing', name_cn: '許靖', faction: 'other', tier: 3 },
  { name_kr: '형도영', name_en: 'Xing Daorong', name_cn: '邢道栄', faction: 'other', tier: 3 },
  { name_kr: '호진', name_en: 'Hu Zhen', name_cn: '胡軫', faction: 'other', tier: 3 },
  { name_kr: '화웅', name_en: 'Hua Xiong', name_cn: '華雄', faction: 'other', tier: 3 },
  { name_kr: '황조', name_en: 'Huang Zu', name_cn: '黄祖', faction: 'other', tier: 3 },
  { name_kr: '후선', name_en: 'Hou Xuan', name_cn: '侯選', faction: 'other', tier: 3 },
  { name_kr: '후성', name_en: 'Hou Cheng', name_cn: '侯成', faction: 'other', tier: 3 },
  { name_kr: '휴고', name_en: 'Sui Gu', name_cn: '眭固', faction: 'other', tier: 3 },
];

export const ALL_CHARACTERS = [...TIER_0, ...TIER_1, ...TIER_2, ...TIER_3];

/**
 * KR→EN, EN→KR, KR→CN 매핑 생성
 */
export function buildNameMap() {
  const kr2en = {}, en2kr = {}, kr2cn = {}, cn2kr = {};
  for (const c of ALL_CHARACTERS) {
    kr2en[c.name_kr] = c.name_en;
    en2kr[c.name_en] = c.name_kr;
    kr2cn[c.name_kr] = c.name_cn;
    cn2kr[c.name_cn] = c.name_kr;
  }
  return { kr2en, en2kr, kr2cn, cn2kr };
}
